--
-- PostgreSQL database dump
--

\restrict v8Ul8FZFJHALcSj1WhXhB0Og5A9cqnOhSVUSxj79wUOPr1Dv5gIX72hsN0eId3n

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-18 10:44:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: certificate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.certificate (
    certificate_id bigint NOT NULL,
    authority character varying(255),
    certificate_name character varying(255),
    expiry_date character varying(255),
    issue_date character varying(255),
    issued_to character varying(255)
);


ALTER TABLE public.certificate OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: certificate_certificate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.certificate ALTER COLUMN certificate_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificate_certificate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5006 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: certificate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.certificate (certificate_id, authority, certificate_name, expiry_date, issue_date, issued_to) FROM stdin;
6	mall	ABC shop	2026-05-30	2026-05-23	fire 
9	fuunction	ABC shop	2026-05-15	2026-05-29	fire 
10	Karnataka Fire Department	Fire Safety	2026-06-26	2026-05-18	Lullu Mall
7	fuunction	Safety	2026-05-30	2026-05-15	employee
11	Karnataka  Department	Licience	2026-05-22	2026-05-18	Mall of asia
\.


--
-- TOC entry 5012 (class 0 OID 0)
-- Dependencies: 219
-- Name: certificate_certificate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.certificate_certificate_id_seq', 11, true);


--
-- TOC entry 4857 (class 2606 OID 16397)
-- Name: certificate certificate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT certificate_pkey PRIMARY KEY (certificate_id);


-- Completed on 2026-05-18 10:44:19

--
-- PostgreSQL database dump complete
--

\unrestrict v8Ul8FZFJHALcSj1WhXhB0Og5A9cqnOhSVUSxj79wUOPr1Dv5gIX72hsN0eId3n

